# nixpacks.toml

[phases.setup]
# Set execute permission for tsc during the setup phase
commands = [
  "yarn cache clean"
]

[phases.build]
# Install dependencies using Yarn and run tsc
commands = [
  "yarn Install",   
  "npx tsc"
]
