# nixpacks.toml

[phases.setup]
# Set execute permission for tsc during the setup phase
commands = [
  "chmod +x ./node_modules/.bin/tsc",
  "chmod +x ./bin/sh",
  "yarn cache clean"
]

[phases.build]
# Install dependencies using Yarn and run tsc
commands = [
  "yarn build"
]
